export enum VehClass {
     Compact = 0,
     Sedan = 1,
     SUV = 2,
     Coupe = 3,
     Muscle = 4,
     SportsClassic = 5,
     Sport = 6,
     Super = 7,
     Motorcycle = 8,
     Offroad = 9,
     Industrial = 10,
     Utility = 11,
     Vans = 12,
     Cycle = 13,
     Boat = 14,
     Helicopter = 15,
     Plane = 16,
     Service = 17,
     Emergency = 18,
     Military = 19,
     Commercial = 20,
     Train = 21,
     OpenWheel = 22,
}