name = 'alt:V Server'
host = '0.0.0.0'
port = 7788
players = 128
# password = 'ultra-password'
announce = false
token = '9ccb1e41-a415-4623-8ea3-4904831155c6'
gamemode = 'Freeroam'
website = 'example.com'
language = 'en'
description = 'alt:V Sample Server'
modules = ['csharp-module']
resources = ['server', 'gabz_pillbox', 'gabz_mrpd', 'assets']
debug = true

[voice]
streamingTickRate = 10
# The bitrate of the voice server
bitrate = 64000
# The secret for the external server (only needed when using externalHost)
# The secret must consist of numeric values only
externalSecret = 1234567890
# The external host address (leave 127.0.0.1, if voice-server is on same machine)
externalHost = "127.0.0.1"
# The external host port
externalPort = 7798
# The external host public address (should be the ip address of your server, not localhost!)
externalPublicHost = "dyn.letsion.de"
# The external host public port
externalPublicPort = 7799