name = 'alt:V Server'
host = '0.0.0.0'
port = 7788
players = 128
# password = 'ultra-password'
announce = false
token = '9ccb1e41-a415-4623-8ea3-4904831155c6'
gamemode = 'Freeroam'
website = 'example.com'
language = 'en'
description = 'alt:V Sample Server'
modules = ['csharp-module']
resources = ['server', 'gabz_pillbox', 'gabz_mrpd', 'assets']
debug = true
